
language: perl
perl:
  - "5.20"
env:
  - "HARNESS_OPTIONS=j9 TEST_EV=1 TEST_POD=1 TEST_SOCKS=1 TEST_TLS=1"
install:
  - "cpanm -n Mojolicious Lingua::EN::Inflect SQL::Abstract EV IO::Socket::Socks IO::Socket::SSL Net::DNS::Native Test::Pod Test::Pod::Coverage"
  - "cpanm -n --installdeps ."
sudo: false
notifications:
  email: false
